### ISSUE TITLE
Write an example module for the new Python API

### ISSUE THREAD

**Issue by vidraj** [vidraj/derinet#1]
The new API is structured in a similar fashion to the Perl API, with modules connected in a pipeline. But there are no modules so far.
Apart from the modules that do some actual work, we also need an example module that would serve as practical documentation of the API. Somebody should write that.

**Comment by vojtsek** [comment]
Sample module and scenario added in commit d353df099043ff23876817399666eaeb25143437

**Comment by vidraj** [comment]
Thanks, that's great! From what I can see it looks quite similar to the Perl API scenarios, which is nice.

I'll take a closer look at it in a few days and I'll start writing scenarios for 1.5 and older versions.

**Comment by vojtsek** [comment]
Yes, I have inspired at Perl :) That would be nice.
