### ISSUE TITLE
Misleading docstrings everywhere

### ISSUE THREAD

**Issue by vidraj** [vidraj/derinet#10]
The docstrings haven't been updated for a while. Many functions have docstrings that don't match their signature, e.g. [get_lexeme()](/vidraj/derinet/blob/9639ef70e6e9fd7ea4aab849d982133493fcac01/tools/data-api/derinet2/derinet/derinet.py#L302), [get_id()](/vidraj/derinet/blob/9639ef70e6e9fd7ea4aab849d982133493fcac01/tools/data-api/derinet2/derinet/derinet.py#L359), [get_parent()](/vidraj/derinet/blob/9639ef70e6e9fd7ea4aab849d982133493fcac01/tools/data-api/derinet2/derinet/derinet.py#L380) and possibly others.

**Comment by vojtsek** [comment]
solved in 4d31a5b103cba64eadee0f30d27a3fd10dd52db0
