### ISSUE TITLE
How to call modules using only a single name?

### ISSUE THREAD

**Issue by vidraj** [vidraj/derinet#14]
In our Python build system, users have the option of writing scenarios, which consist of several modules. They do this by specifying the module names (and options), which are then searched for by the scenario manager, the appropriate Python classes are initialized and executed and the results are logged.

Currently, users have to specify both file names and class names of the modules, because the scenario manager must know both pieces of information before it can find and launch the module. I find this suboptimal and I would like to make writing scenarios better and easier.

This modular system should ideally work similarly to the older `derimor` system written in Perl, or the `Treex` system it was inspired by. There, classes and the paths to their sources correspond 1:1. For example, the module `CS::AddLexemesFromList` is found in a file called `DerivMorpho/Block/CS/AddLexemesFromList.pm`.

In Python, the correspondence is less clear due to the naming convention. It is usual that module names (and therefore file names) are written in lower_case_with_underscores, while class names are in CamelCase. This is what makes finding the modules problematic.

I see three possible solutions:
1) Use CamelCase everywhere, maintaining continuity with Perl, breaking the Python module naming convention,
2) use underscored_lowercase everywhere, breaking the Python class naming convention,
3) convert between the two representation at runtime. This is wonky when dealing with classes like `StartHTTPConnection`, which should correspond to file `start_http_connection.py` – it's not clear where to put the underscores and what to capitalize.

I like option 1 the most.

**Comment by vidraj** [comment]
Udapi-python uses the following strategy:
* Follow the standard Python convention for class names.
* Use class names as module identifiers in the scenarios.
* Derive file names by lowercasing the class names without further changes (esp. without underscores).

If nobody objects, I'll implement this as well.

**Comment by vojtsek** [comment]
Hi,

yeah it will simplify the use case, no objections.

The convention is just a convention, I do not insist on it, so if you want, please implement it.

However, yet another solution would be to add import line for every module to modules/\_\_init.py\_\_ explicitly.
This way we could just `from modules import DesiredModule`

**Comment by vidraj** [comment]
Oh, I didn't think of that, thank you for the suggestion! It is actually pretty clean and would allow us to stick to the recommended naming schemes. But it requires maintaining extra linkage code, which I don't like.

**Comment by vidraj** [comment]
I guess that as long as we keep the scenarios themselves backwards compatible, we can change the inner mechanics as we see fit – which includes potentially renaming files.

So I'll go ahead with the Udapi/Treex/derimor strategy, including the way of specifying parameters using `key=value` pairs. It's known to work and to be simple enough.
