### ISSUE TITLE
Structure the exceptions using subclasses

### ISSUE THREAD

**Issue by vidraj** [vidraj/derinet#2]
The methods of the new Python API can throw many different custom exceptions. There is usually no good programmatical way of reacting to them, except for catching them and logging the affected lexemes for further annotation.
Since they are only subclassing `Exception`, we can't catch them by writing a simple short statement without also catching `RuntimeError`, `IndexError` and other exceptions that we don't want to catch.
If we introduce a superclass `DeriNetException`, we'll be able to catch them all by catching this exception.

**Comment by vojtsek** [comment]
Should be solved in 4e925e118228ac2b7398db0e3c97442ffbec31cb
