### ISSUE TITLE
get_parent() doesn't throw on nonexistent lexemes

### ISSUE THREAD

**Issue by vidraj** [vidraj/derinet#9]
Most functions should throw LexemeNotFoundError when a lexeme specified by ID is not found. At least get_parent() doesn't do that, making it impossible to distinguish between errors and simply nonexisting parents.

We can relax this requirement for lexemes specified by lemma-techlemma-pos combination.

**Comment by vojtsek** [comment]
solved by 9ee2ad9e6a8c30e69bf3b12cf7df461ea450c7ed
